apiVersion: v1
kind: Service
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr
  labels:
    app: {{ template "alfresco-search.fullName" . }}-solr
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      name: {{ .Values.service.name }}
  clusterIP: None
  selector:
    app: {{ template "alfresco-search.fullName" . }}-solr
